#!/bin/sh

depcheck(){
	if [ -e "/usr/bin/nasm" ]; then
		echo "nasm found: running init..."
	else
		echo "nasm not installed. Exiting..."
		exit 0;
	fi
}

init(){
	if [ -d "./TEMP" ]; then
		echo "Program failed to exit correctly in instance."
		echo "Recompiling binary..."
		rm -rf ./TEMP
		mkdir ./TEMP
		nasm -o ./TEMP/bootmark.bin ./sources/bootmark.asm
		echo "Success"
	else
		mkdir ./TEMP
		echo "Compiling binary..."
		nasm -o ./TEMP/bootmark.bin ./sources/bootmark.asm
		echo "Success"
	fi
}

depcheck
init

sudo dd ibs=2 obs=1 seek=510 count=1 if=./TEMP/bootmark.bin of=$1

rm -rf ./TEMP

exit 0
