#!/bin/sh

#this is an interactive raw disk imaging formatter used to create boot disks for the osmium kernel.

#this is auto formated to just generate a mbr
blocksize="512"
blocks="1"
disk="/tmp/Osmium_src/disk.img"

#remove old default if one exists.
if [ -e "/tmp/Osmium_src/disk.img" ];then
	echo "oops... someone made a default disk and shoved it in the temporary folder!"
	echo "would you like me to remove that for you?"
	while true; do
		read yn
		case $yn in
			[Yy]*)rm "/tmp/Osmimum_src/disk.img";break;;
			[Nn]*)break;;
			*)echo "I'm not sure I heard that clearly... WAT!? [Yy] [Nn]";;
		esac
	done
fi


#prints help message
_help_(){
	
}

#generate new disk of specified size.
_new_(){
	if [ $1 != "" ];then
		out=$1
	fi
	dd bs=$blocksize count=
}

launch_script(){
	return exec ./$1
}
