#!/bin/sh

depcheck(){
	if [ -e "/usr/bin/nasm" ]; then
		echo "nasm found: running init..."
	else
		echo "nasm not installed. Exiting..."
		exit 0;
	fi
}

init(){
	if [ -e "/tmp/Osmium_src/bootmark.bin" ]; then
		echo "Program failed to exit correctly in last instance."
		echo "Recompiling binary..."
		rm -rf /tmp/Osmium_src/bootmark.bin
		mkdir /tmp/Osmium_src
		nasm -o /tmp/Osmium_src/bootmark.bin ./../sources/bootmark.asm
		echo "Success"
	else
		mkdir /tmp/Osmium_src
		echo "Compiling binary..."
		nasm -o /tmp/Osmium_src/bootmark.bin ./../sources/bootmark.asm
		echo "Success"
	fi
}

depcheck
init

sudo dd ibs=2 obs=1 seek=510 count=1 if=/tmp/Osmium_src/bootmark.bin of=$1

rm -rf /tmp/Osmium_src/bootmark.bin

exit 0
